# Add 'kernel' label to any change within the 'dotnet/src' that's not 'SemanticKernel' or 'SemanticKernel.Abstractions' directory
kernel:
  - any: ["dotnet/src/**/*", "dotnet/src/*"]
  - all:
      [
        "!dotnet/src/SemanticKernel/*",
        "!dotnet/src/SemanticKernel/**/*",
        "!dotnet/src/SemanticKernel.Abstractions/*",
        "!dotnet/src/SemanticKernel.Abstractions/**/*",
      ]

# Add 'kernel.core' label to any change within the 'SemanticKernel' or 'SemanticKernel.Abstractions' directory
kernel.core:
  - dotnet/src/SemanticKernel/*
  - dotnet/src/SemanticKernel/**/*
  - dotnet/src/SemanticKernel.Abstractions/*
  - dotnet/src/SemanticKernel.Abstractions/**/*

# Add 'python' label to any change within the 'python' directory
python:
  - python/*
  - python/**/*

# Add 'samples' label to any change within the 'samples' directory
samples:
  - samples/*
  - samples/**/*

# Add '.NET' label to any change within samples or kernel 'dotnet' directories.
.NET:
  - dotnet/src/*
  - dotnet/src/**/*
  - samples/**/dotnet/**/*
  - samples/**/dotnet/*
