name: Run Java Integration Tests and Samples

on:
  workflow_dispatch:
  push:
    branches: [ "experimental-java", "java-dev" ]
    paths:
      - 'java/**'
      - 'samples/java/**'
  pull_request:
    branches: [ "experimental-java", "java-dev" ]
    paths:
      - 'java/**'
      - 'samples/java/**'

permissions:
  contents: read

jobs:
  java-integration-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-versions: [8, 11, 17]

    name: Java Tests on JDK${{ matrix.java-versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Need to use JDK 11 to build for JDK 8
      - name: Set JDK
        id: set-jdk
        shell: bash
        run: |
          if [[ ${{ matrix.java-versions }} == 8 ]]; then
            echo "JDK_VERSION=11" >> $GITHUB_OUTPUT
          else
            version=${{ matrix.java-versions }}
            echo "JDK_VERSION=$version" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.set-jdk.outputs.JDK_VERSION }}
          distribution: microsoft
          cache: maven

      - name: Build with Maven
        run: ./mvnw -B -Pbug-check -DskipTests -Pcompile-jdk${{ matrix.java-versions }} clean install --file pom.xml
        working-directory: java

      # API tests run on JDK 17+
      - name: Run integration tests
        run: ../mvnw -B -Pbug-check -Pcompile-jdk${{ matrix.java-versions }} clean install --file pom.xml
        working-directory: java/api-test
        env:
          OPENAI_API_KEY: ""
          AZURE_OPENAI_ENDPOINT: ""
          AZURE_OPENAI_API_KEY: ""
          AZURE_OPENAI_DEPLOYMENT_NAME: ""
        if: ${{ matrix.java-versions >= 17 }}

      # Samples build on JDK 17+
      - name: Build semantic-kernel samples
        run: ../../../java/mvnw -B -Pcompile-jdk${{ matrix.java-versions }} clean install --file pom.xml
        working-directory: samples/java/semantickernel-samples
        if: ${{ matrix.java-versions >= 17 }}
