name: Build Java Semantic Kernel

on:
  workflow_dispatch:
  push:
    branches: [ "experimental-java", "java-dev" ]
    paths:
      - 'java/**'
  pull_request:
    branches: [ "experimental-java", "java-dev" ]
    paths:
      - 'java/**'

permissions:
  contents: read

jobs:
  java-build:
    name: Java CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-versions: [jdk8, jdk11, jdk17]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # Need to use different JDK for JDK 8
      - name: Set JDK
        id: set-jdk
        shell: bash
        run: |
          if [[ ${{ matrix.java-versions }} == "jdk8" ]]; then
            echo "JDK_VERSION=11" >> $GITHUB_OUTPUT
          else
            version=$(echo ${{ matrix.java-versions }} | sed 's/jdk//')
            echo "JDK_VERSION=$version" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.set-jdk.outputs.JDK_VERSION }}
          distribution: temurin
          cache: maven

      - name: Build with Maven
        run: ./mvnw -B -Pbug-check -DskipTests -X -Pcompile-${{ matrix.java-versions }} clean install --file pom.xml
        working-directory: java

      - name: Run tests
        run: ./mvnw -B -Pbug-check -DskipITs test --file pom.xml
        working-directory: java

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test_output_sk_jdk${{ matrix.java-versions }}u
          path: java/**/target/surefire-reports/*Test.txt
