name: Build Java Semantic Kernel

on:
  workflow_dispatch:
  push:
    branches: [ "experimental-java", "java-dev" ]
  pull_request:
    branches: [ "experimental-java", "java-dev" ]

permissions:
  contents: read

jobs:
  java-build:
    name: Java CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [8, 11, 17]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}

        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: Build with Maven
        run: ./mvnw -DskipTests -B -Pbug-check clean install --file pom.xml
        working-directory: java

      - name: Run tests
        run: ./mvnw -B -Pbug-check test --file pom.xml
        working-directory: java

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test_output_sk_jdk${{ matrix.java }}u
          path: java/**/target/surefire-reports/*Test.txt
