name: Add title prefix
on:
  issues:
    types: [ labeled ]
  pull_request:
    types: [ labeled ]

jobs:
  add_title_prefix:
    name: "Issue/PR: add title prefix"
    # Define a matrix of label and prefix pairs
    strategy:
      matrix:
        include:
          - {label: 'python', prefix: 'Python: '}
          - {label: 'java', prefix: 'Java: '}

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      
    steps:
      - uses: actions/github-script@v6
        name: "Issue/PR: update title"
        with:
          script: |
            // Get the event name, title and labels
            let title
            const labels
            if (eventName == 'issues') {
              title = context.payload.issue.title
              labels = context.payload.issue.labels.map(label => label.name)
            } else {
              title = context.payload.pull_request.title
              labels = context.payload.pull_request.labels.map(label => label.name)
            }
            
            labelAdded = ${{ github.event.label.name }}
            
            let originalTitle = title
            
            // Get the label and prefix from the matrix
            const label = ${{ matrix.label }}
            const prefix = ${{ matrix.prefix }}

            // Update the title based on the label and prefix
            // Check if the issue or PR has the label
            if (labels.includes(label)) {
              // Check if the title starts with the prefix (case-sensitive)
              if (!title.startsWith(prefix)) {
                // If not, check if the first word is the label (case-insensitive)
                if (title.match(new RegExp(`^${label}`, 'i'))) {
                  // If yes, replace it with the prefix (case-sensitive)
                  title = title.replace(new RegExp(`^${label}`, 'i'), prefix)
                } else {
                  // If not, prepend the prefix to the title
                  title = prefix + title
                }
              }
            }
            
            // Update the issue or PR title, if changed
            if (title != originalTitle ) {
              if (eventName == 'issues') {
                github.rest.issues.update({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: title
                });
              } else {
                github.rest.pulls.update({
                  pull_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: title
                });
              }
            }
