name: Add title prefix
on:
  issues:
    types: [ labeled ]
  pull_request:
    types: [ labeled ]

jobs:
  add_title_prefix:
    name: "Issue/PR: add title prefix"
    # Define a matrix of label and prefix pairs
    strategy:
      matrix:
        include:
          - {label: 'python', prefix: 'Python'}
          - {label: 'java', prefix: 'Java'}
          - {label: '.NET', prefix: '.Net'}
          - {label: 'copilot chat', prefix: 'Copilot Chat'}

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      
    steps:
      - uses: actions/github-script@v6
        name: "Issue/PR: update title"
        with:
          script: |
            // Get the label and prefix from the matrix
            const label = '${{ matrix.label }}'
            const prefix = '${{ matrix.prefix }}'
            
            labelAdded = '${{ github.event.label.name }}'
          
            // Get the event name, title and labels
            let title
            if (context.event_name == 'issues') {
              title = context.payload.issue.title
            } else {
              title = context.payload.pull_request.title
            }
            
            let originalTitle = title

            // Update the title based on the label and prefix
            // Check if the issue or PR has the label
            if (labelAdded == label) {
              // Check if the title starts with the prefix (case-sensitive)
              if (!title.startsWith(prefix + ": ")) {
                // If not, check if the first word is the label (case-insensitive)
                if (title.match(new RegExp(`^${prefix}`, 'i'))) {
                  // If yes, replace it with the prefix (case-sensitive)
                  title = title.replace(new RegExp(`^${prefix}`, 'i'), prefix)
                } else {
                  // If not, prepend the prefix to the title
                  title = prefix + ": " + title
                }
              }
            }
            
            // Update the issue or PR title, if changed
            if (title != originalTitle ) {
              if (context.event_name == 'issues') {
                github.rest.issues.update({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: title
                });
              } else {
                github.rest.pulls.update({
                  pull_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: title
                });
              }
            }
